const PATH_SAMPLES = 'test/sample';
const PATH_SAMPLE_SIMPLE_JS = PATH_SAMPLES + '/simple.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS =
	PATH_SAMPLES + '/simple.imports.scss.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS =
	PATH_SAMPLES + '/simple.imports.sass.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS_COMPILED =
	PATH_SAMPLES + '/simple.imports.sass.compiled.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS_COMPILED =
	PATH_SAMPLES + '/simple.imports.scss.compiled.js';
const PATH_SAMPLE_SIMPLE_JS_COMPILED = PATH_SAMPLES + '/simple.compiled.js';
const PATH_SAMPLE_OUTFILE = 'build/test.js';
const PATH_SAMPLE_SIMPLE_SCSS = PATH_SAMPLES + '/simple.scss';
const PATH_SAMPLE_SIMPLE_SASS = PATH_SAMPLES + '/simple.sass';
const PATH_SAMPLE_SIMPLE_SCSS_COMPILED =
	PATH_SAMPLES + '/simple.compiled.scss.css';
const PATH_SAMPLE_SIMPLE_SASS_COMPILED =
	PATH_SAMPLES + '/simple.compiled.sass.css';
const PATH_SAMPLE_SIMPLE_IMPORT_SCSS_COMPILED =
	PATH_SAMPLES + '/simple.compiled.import.scss.css';
const PATH_SAMPLE_SIMPLE_IMPORT_SASS_COMPILED =
	PATH_SAMPLES + '/simple.compiled.import.sass.css';

export
	{ PATH_SAMPLES
	, PATH_SAMPLE_SIMPLE_JS
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS_COMPILED
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS_COMPILED
	, PATH_SAMPLE_SIMPLE_JS_COMPILED
	, PATH_SAMPLE_OUTFILE
	, PATH_SAMPLE_SIMPLE_SCSS
	, PATH_SAMPLE_SIMPLE_SASS
	, PATH_SAMPLE_SIMPLE_SCSS_COMPILED
	, PATH_SAMPLE_SIMPLE_SASS_COMPILED
	, PATH_SAMPLE_SIMPLE_IMPORT_SCSS_COMPILED
	, PATH_SAMPLE_SIMPLE_IMPORT_SASS_COMPILED
	};
