const PATH_SAMPLES = 'test/sample';
const PATH_SAMPLE_SIMPLE_JS = PATH_SAMPLES + '/simple.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS =
	PATH_SAMPLES + '/simple.imports.scss.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS =
	PATH_SAMPLES + '/simple.imports.sass.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS_COMPILED =
	PATH_SAMPLES + '/simple.imports.sass.compiled.js';
const PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS_COMPILED =
	PATH_SAMPLES + '/simple.imports.scss.compiled.js';
const PATH_SAMPLE_SIMPLE_JS_COMPILED = PATH_SAMPLES + '/simple.compiled.js';
const PATH_SAMPLE_OUTFILE = 'build/test.js';
const PATH_SAMPLE_SIMPLE_SCSS = PATH_SAMPLES + '/simple.scss';
const PATH_SAMPLE_SIMPLE_SASS = PATH_SAMPLES + '/simple.sass';
const PATH_SAMPLE_SIMPLE_SCSS_COMPILED =
	PATH_SAMPLES + '/simple.compiled.scss.css';
const PATH_SAMPLE_SIMPLE_SASS_COMPILED =
	PATH_SAMPLES + '/simple.compiled.sass.css';
const PATH_SAMPLE_POSTCSS = PATH_SAMPLES + '/postcss.scss';
const PATH_SAMPLE_POSTCSS_COMPILED = PATH_SAMPLES + '/postcss.compiled.css';
const PATH_SAMPLE_POSTCSS_SOURCEMAP_COMPILED =
	PATH_SAMPLES + '/postcss.sourcemap.compiled.css';
const PATH_SAMPLE_INLINE_JS = PATH_SAMPLES + '/inline.js';
const PATH_SAMPLE_INLINE_JS_COMPILED = PATH_SAMPLES + '/inline.compiled.js';
const PATH_SAMPLE_FILE_JS = PATH_SAMPLES + '/file.js';
const PATH_SAMPLE_FILE_JS_COMPILED = PATH_SAMPLES + '/file.compiled.js';
const PATH_SAMPLE_SIMPLE_UNRESOLVING = PATH_SAMPLES + '/simple.unresolving.js';
const PATH_SAMPLE_INLINE_UNRESOLVING = PATH_SAMPLES + '/inline.unresolving.js';
const PATH_SAMPLE_FILE_UNRESOLVING = PATH_SAMPLES + '/file.unresolving.js';
const PATH_SAMPLE_DYNAMIC_SIMPLE_JS = PATH_SAMPLES + '/dynamic.simple.js';
const PATH_SAMPLE_DYNAMIC_SIMPLE_JS_COMPILED =
	PATH_SAMPLES + '/dynamic.simple.compiled.js';

export
	{ PATH_SAMPLES
	, PATH_SAMPLE_SIMPLE_JS
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SASS_COMPILED
	, PATH_SAMPLE_SIMPLE_JS_IMPORT_SCSS_COMPILED
	, PATH_SAMPLE_SIMPLE_JS_COMPILED
	, PATH_SAMPLE_OUTFILE
	, PATH_SAMPLE_SIMPLE_SCSS
	, PATH_SAMPLE_SIMPLE_SASS
	, PATH_SAMPLE_SIMPLE_SCSS_COMPILED
	, PATH_SAMPLE_SIMPLE_SASS_COMPILED
	, PATH_SAMPLE_POSTCSS
	, PATH_SAMPLE_POSTCSS_COMPILED
	, PATH_SAMPLE_POSTCSS_SOURCEMAP_COMPILED
	, PATH_SAMPLE_INLINE_JS
	, PATH_SAMPLE_INLINE_JS_COMPILED
	, PATH_SAMPLE_FILE_JS
	, PATH_SAMPLE_FILE_JS_COMPILED
	, PATH_SAMPLE_SIMPLE_UNRESOLVING
	, PATH_SAMPLE_INLINE_UNRESOLVING
	, PATH_SAMPLE_FILE_UNRESOLVING
	, PATH_SAMPLE_DYNAMIC_SIMPLE_JS
	, PATH_SAMPLE_DYNAMIC_SIMPLE_JS_COMPILED
	};
